#!/usr/bin/env node
// Builds the gallery site from games/*/meta.json.
//   node tools/hub.mjs [--out site] [--games games] [--skip-invalid]
// Output (relative links only, so the same folder works on GitHub Pages and on itch.io via butler):
//   site/index.html          Japanese-first gallery with an English toggle, newest game first
//   site/<dir>/index.html    copy of each game with a small "← 一覧へ" link injected (originals untouched)
//   site/games.json          the list of games (meta + path) for other tools
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readMeta, validateMeta, parseArgs, escapeHtml } from './lib/common.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARKER = '.hub-generated';
const REPO_URL = 'https://github.com/kohei8443-byte/ai-weekly-arcade';
export const DISCLOSURE = {
  ja: 'コードはAI（Claude）、絵と音はコードで生成、判断するのは人間（kouhei）',
  en: 'Code by AI (Claude). Art and sound are generated by code. A human (kouhei) makes the calls.'
};

// ---------- back link injected into each game copy ----------
const BACK_LINK = `
<!-- injected by tools/hub.mjs (site copy only) -->
<a id="awa-back" href="../index.html">&larr; 一覧へ</a>
<style>
#awa-back{position:fixed;left:max(8px,env(safe-area-inset-left));bottom:max(8px,env(safe-area-inset-bottom));z-index:2147483647;
font:700 12px/1 system-ui,-apple-system,"Hiragino Sans","Noto Sans JP",sans-serif;color:#fff;background:rgba(10,12,30,.62);
border:1px solid rgba(255,255,255,.28);padding:8px 12px;border-radius:999px;text-decoration:none;opacity:.8;
-webkit-tap-highlight-color:transparent;touch-action:manipulation;-webkit-user-select:none;user-select:none}
#awa-back:hover,#awa-back:focus-visible{opacity:1}
#awa-back:focus-visible{outline:2px solid #ffd36e;outline-offset:2px}
</style>
<script>
(function () {
  var a = document.getElementById('awa-back');
  if (!a) return;
  if (/[?&]demo=1(&|$)/.test(location.search)) { a.parentNode.removeChild(a); return; }
  try { if (localStorage.getItem('awa-lang') === 'en') a.innerHTML = '&larr; All games'; } catch (e) {}
  // keep the game from treating this tap as gameplay, and navigate even if the game blocks default touch actions
  var go = function (e) { e.preventDefault(); e.stopPropagation(); location.href = a.href; };
  a.addEventListener('pointerdown', function (e) { e.stopPropagation(); });
  a.addEventListener('touchend', go);
  a.addEventListener('click', go);
})();
</script>
`;

export function injectBackLink(html) {
  const i = html.toLowerCase().lastIndexOf('</body>');
  return i < 0 ? html + BACK_LINK : html.slice(0, i) + BACK_LINK + html.slice(i);
}

// ---------- gallery page ----------
// Golden-angle steps give neighbouring weeks clearly different colours.
const hueOf = week => Math.round((200 + week * 137.508) % 360);

function card(g, i) {
  const m = g.meta;
  const e = escapeHtml;
  const nn = String(m.week).padStart(2, '0');
  const hue = hueOf(m.week);
  const href = `${encodeURI(g.dir)}/index.html`;
  const mins = Math.max(1, Math.round(m.session_length_sec / 60));
  // Below 2 minutes, seconds read better than a rounded "about 2 min" (90 s would round up to 2).
  const len = m.session_length_sec < 120
    ? { ja: `1回 約${m.session_length_sec}秒`, en: `~${m.session_length_sec} s per run` }
    : { ja: `1回 約${mins}分`, en: `~${mins} min per run` };
  return `
  <article class="card${i === 0 ? ' newest' : ''}" style="--h:${hue}">
    <a class="art" href="${href}" tabindex="-1" aria-hidden="true">
      <span class="num">#${nn}</span>
      ${i === 0 ? '<span class="badge"><span class="ja">最新作</span><span class="en">NEW</span></span>' : ''}
    </a>
    <div class="body">
      <div class="week"><span class="ja">第${m.week}週</span><span class="en">Week ${m.week}</span> · <span class="genre">${e(m.genre)}</span></div>
      <h2><a href="${href}"><span class="ja">${e(m.title_ja)}</span><span class="en">${e(m.title_en)}</span></a></h2>
      <p class="tagline"><span class="ja">${e(m.tagline_ja)}</span><span class="en">${e(m.tagline_en)}</span></p>
      <details>
        <summary><span class="ja">あそびかた</span><span class="en">How to play</span></summary>
        <p><span class="ja">${e(m.how_to_play_ja)}</span><span class="en">${e(m.how_to_play_en)}</span></p>
        <ul class="controls">${m.controls.map(c => `<li>${e(c)}</li>`).join('')}</ul>
      </details>
      <div class="foot">
        <span class="len"><span class="ja">${len.ja}</span><span class="en">${len.en}</span></span>
        <a class="play" href="${href}"><span class="ja">あそぶ</span><span class="en">Play</span></a>
      </div>
    </div>
  </article>`;
}

function galleryHtml(games, builtAt) {
  const favicon = "data:image/svg+xml," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#141a4a"/><circle cx="32" cy="32" r="13" fill="#ffd36e"/><circle cx="32" cy="32" r="23" fill="none" stroke="#7fe3c4" stroke-width="4" stroke-dasharray="6 6"/></svg>');
  const count = games.length;
  return `<!doctype html>
<html lang="ja" data-lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0d1030">
<title>AI Weekly Arcade | AIが毎週つくるゲーム</title>
<meta name="description" content="Claude が毎週1本つくる、スマホで遊べる小さなブラウザゲーム集です。${escapeHtml(DISCLOSURE.ja)}。">
<meta property="og:title" content="AI Weekly Arcade | AIが毎週つくるゲーム">
<meta property="og:description" content="Claude が毎週1本つくる、スマホで遊べる小さなブラウザゲーム集です。">
<link rel="icon" href="${favicon}">
<style>
:root {
  --bg: #0d1030; --bg2: #151a46; --card: #1a1f52; --ink: #f6efe0; --dim: #a5aad6; --line: #ffffff1f;
  --accent: #ffd36e; --accent-ink: #1a1405; --mint: #7fe3c4; --coral: #ff7a6b;
  --font: system-ui, -apple-system, "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Noto Sans JP", "Yu Gothic", "Meiryo", sans-serif;
  color-scheme: dark;
}
[hidden] { display: none !important; }
html[data-lang="ja"] .en, html[data-lang="en"] .ja { display: none !important; }
* { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0; min-height: 100vh; background: radial-gradient(120% 60% at 50% 0%, var(--bg2) 0%, var(--bg) 60%) var(--bg) fixed;
  color: var(--ink); font-family: var(--font); line-height: 1.6;
}
a { color: inherit; }
.wrap { max-width: 1080px; margin: 0 auto; padding-left: max(16px, env(safe-area-inset-left)); padding-right: max(16px, env(safe-area-inset-right)); }
header { padding-top: 28px; padding-bottom: 8px; }
.top { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
.kicker { font-size: 12px; font-weight: 800; letter-spacing: .28em; color: var(--mint); }
h1 { margin: 4px 0 0; font-size: clamp(26px, 7.8vw, 52px); text-wrap: balance; line-height: 1.1; font-weight: 900; letter-spacing: .01em; }
h1 b { color: var(--accent); }
.nb { display: inline-block; }
.lead { margin: 12px 0 0; color: var(--dim); font-size: 15px; max-width: 40em; }
.toggle {
  flex: none; font: 800 13px/1 var(--font); color: var(--ink); background: #ffffff14; border: 1px solid var(--line);
  border-radius: 999px; padding: 10px 14px; cursor: pointer; min-width: 52px; min-height: 40px;
}
.toggle:focus-visible, .play:focus-visible, summary:focus-visible, h2 a:focus-visible { outline: 2px solid var(--accent); outline-offset: 3px; }
.meta-line { margin: 18px 0 0; font-size: 13px; color: var(--dim); }
main { padding-top: 16px; padding-bottom: 8px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 300px), 1fr)); gap: 16px; }
.card {
  position: relative; display: flex; flex-direction: column; background: var(--card); border-radius: 18px; overflow: hidden;
  border: 1px solid var(--line); box-shadow: 0 10px 30px #00000040;
}
.card.newest { border-color: #ffd36e66; }
.art {
  position: relative; display: block; aspect-ratio: 16 / 7; text-decoration: none; overflow: hidden;
  background:
    radial-gradient(circle at 78% 30%, hsl(calc(var(--h) + 40) 85% 70% / .9) 0 14%, transparent 15%),
    radial-gradient(circle at 78% 30%, transparent 0 24%, hsl(calc(var(--h) + 40) 85% 75% / .35) 24.5% 25.5%, transparent 26%),
    radial-gradient(circle at 20% 120%, hsl(var(--h) 80% 60% / .55) 0 35%, transparent 36%),
    linear-gradient(135deg, hsl(var(--h) 60% 26%), hsl(calc(var(--h) + 60) 55% 18%));
}
.num { position: absolute; left: 16px; bottom: 8px; font-size: 56px; font-weight: 900; line-height: 1; color: #ffffffe6; letter-spacing: -.02em; text-shadow: 0 3px 0 #00000040; font-variant-numeric: tabular-nums; }
.badge { position: absolute; right: 12px; top: 12px; font-size: 12px; font-weight: 900; letter-spacing: .1em; color: var(--accent-ink); background: var(--accent); border-radius: 999px; padding: 4px 10px; }
.body { display: flex; flex-direction: column; gap: 6px; padding: 14px 16px 16px; flex: 1; }
.week { font-size: 12px; font-weight: 800; letter-spacing: .08em; color: var(--mint); }
.genre { color: var(--dim); font-weight: 700; letter-spacing: 0; }
h2 { margin: 0; font-size: 22px; line-height: 1.3; font-weight: 900; }
h2 a { text-decoration: none; }
.tagline { margin: 0; font-size: 15px; color: var(--ink); }
details { font-size: 14px; color: var(--dim); }
summary { cursor: pointer; font-weight: 800; color: var(--ink); padding: 4px 0; min-height: 32px; }
details p { margin: 4px 0 8px; }
.controls { display: flex; flex-wrap: wrap; gap: 6px; list-style: none; margin: 0; padding: 0; }
.controls li { font-size: 12px; font-weight: 700; color: var(--ink); background: #ffffff12; border: 1px solid var(--line); border-radius: 6px; padding: 2px 8px; }
.foot { margin-top: auto; padding-top: 8px; display: flex; align-items: center; justify-content: space-between; gap: 12px; }
.len { font-size: 13px; color: var(--dim); font-weight: 700; }
.play {
  display: inline-flex; align-items: center; justify-content: center; min-height: 44px; padding: 0 26px; border-radius: 999px;
  background: var(--accent); color: var(--accent-ink); font-weight: 900; font-size: 16px; text-decoration: none; letter-spacing: .04em;
  box-shadow: 0 4px 0 #c99a2e;
}
.play:active { transform: translateY(2px); box-shadow: 0 2px 0 #c99a2e; }
.empty { color: var(--dim); padding: 40px 0; text-align: center; }
footer { padding-top: 24px; padding-bottom: calc(28px + env(safe-area-inset-bottom)); color: var(--dim); font-size: 13px; border-top: 1px solid var(--line); margin-top: 24px; }
footer .ai { color: var(--ink); font-weight: 800; font-size: 14px; }
footer p { margin: 6px 0; }
@media (prefers-reduced-motion: reduce) { .play:active { transform: none; } }
</style>
</head>
<body>
<header class="wrap">
  <div class="top">
    <div>
      <div class="kicker">AI WEEKLY ARCADE</div>
      <h1><span class="ja"><span class="nb">AIが<b>毎週</b></span><span class="nb">つくるゲーム</span></span><span class="en">A new <b>AI-made</b> game every week</span></h1>
    </div>
    <button class="toggle" id="langToggle" type="button" aria-label="English / 日本語">EN</button>
  </div>
  <p class="lead">
    <span class="ja">Claude が毎週1本、スマホでもPCでも遊べる小さなゲームを作ります。公開するかどうかは kouhei が実際に遊んで決めています。インストール不要、ブラウザでそのまま遊べます。</span>
    <span class="en">Every week Claude builds one small game that runs in your browser on phone or PC. kouhei plays each one and decides whether it ships. No install needed.</span>
  </p>
  <p class="meta-line"><span class="ja">${count}本公開中</span><span class="en">${count} game${count === 1 ? '' : 's'} so far</span></p>
</header>
<main class="wrap">
  ${count ? `<div class="grid">${games.map(card).join('\n')}
  </div>` : '<p class="empty"><span class="ja">まだゲームがありません。</span><span class="en">No games yet.</span></p>'}
</main>
<footer class="wrap">
  <p class="ai"><span class="ja">${escapeHtml(DISCLOSURE.ja)}</span><span class="en">${escapeHtml(DISCLOSURE.en)}</span></p>
  <p><span class="ja">ゲームのコードはすべて公開しています。</span><span class="en">All game code is public.</span> <a href="${REPO_URL}" target="_blank" rel="noopener">GitHub</a></p>
  <p><span class="ja">更新日</span><span class="en">Updated</span> ${escapeHtml(builtAt)}</p>
</footer>
<script>
(function () {
  var root = document.documentElement, btn = document.getElementById('langToggle');
  function apply(l) {
    root.setAttribute('data-lang', l); root.lang = l;
    btn.textContent = l === 'ja' ? 'EN' : 'JA';
    document.title = l === 'ja' ? 'AI Weekly Arcade | AIが毎週つくるゲーム' : 'AI Weekly Arcade | A new AI-made game every week';
  }
  var l = 'ja';
  var q = /[?&]lang=(ja|en)(?:&|$)/.exec(location.search);
  try { var s = localStorage.getItem('awa-lang'); if (s === 'ja' || s === 'en') l = s; } catch (e) {}
  if (q) l = q[1];
  apply(l);
  btn.addEventListener('click', function () {
    l = l === 'ja' ? 'en' : 'ja'; apply(l);
    try { localStorage.setItem('awa-lang', l); } catch (e) {}
  });
})();
</script>
</body>
</html>
`;
}

// ---------- build ----------
function safeToClean(out) {
  const abs = path.resolve(out);
  if (abs === ROOT || ROOT.startsWith(abs + path.sep) || abs === path.parse(abs).root) return false;
  if (!fs.existsSync(abs)) return true;
  const entries = fs.readdirSync(abs);
  return entries.length === 0 || entries.includes(MARKER);
}

export function buildSite({ out, gamesDir, skipInvalid = false, log = console.log }) {
  if (!fs.existsSync(gamesDir)) throw new Error(`games folder not found: ${gamesDir}`);
  if (!safeToClean(out)) throw new Error(`refusing to overwrite ${out}: it is not empty and was not made by hub.mjs`);
  const games = [], problems = [];
  for (const dir of fs.readdirSync(gamesDir).sort()) {
    const full = path.join(gamesDir, dir);
    if (!fs.statSync(full).isDirectory() || dir.startsWith('.') || dir.startsWith('_')) continue;
    const htmlFile = path.join(full, 'index.html');
    if (!fs.existsSync(htmlFile)) { problems.push(`${dir}: index.html is missing`); continue; }
    const { meta, error } = readMeta(full);
    if (error) { problems.push(`${dir}: ${error}`); continue; }
    const { errors } = validateMeta(meta, dir);
    if (errors.length) { problems.push(`${dir}: ${errors.join('; ')}`); continue; }
    games.push({ dir, meta, htmlFile });
  }
  if (problems.length) {
    for (const p of problems) log(`hub: ${skipInvalid ? 'skipped' : 'invalid'} ${p}`);
    if (!skipInvalid) throw new Error(`${problems.length} game folder(s) are invalid (use --skip-invalid to build without them)`);
  }
  const seen = new Map();
  for (const g of games) {
    if (seen.has(g.meta.week)) log(`hub: warning: week ${g.meta.week} is used by both ${seen.get(g.meta.week)} and ${g.dir}`);
    seen.set(g.meta.week, g.dir);
  }
  games.sort((a, b) => b.meta.week - a.meta.week || b.dir.localeCompare(a.dir));

  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, MARKER), 'This folder is generated by tools/hub.mjs. Do not edit; it is rebuilt from games/.\n');
  fs.writeFileSync(path.join(out, '.nojekyll'), '');
  for (const g of games) {
    fs.mkdirSync(path.join(out, g.dir), { recursive: true });
    fs.writeFileSync(path.join(out, g.dir, 'index.html'), injectBackLink(fs.readFileSync(g.htmlFile, 'utf8')));
  }
  const builtAt = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
  fs.writeFileSync(path.join(out, 'index.html'), galleryHtml(games, builtAt));
  fs.writeFileSync(path.join(out, 'games.json'), JSON.stringify(games.map(g => ({ path: `${g.dir}/index.html`, ...g.meta })), null, 2) + '\n');
  return games;
}

async function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2), { out: 'string', games: 'string', 'skip-invalid': 'bool', help: 'bool' });
  } catch (e) { console.error(e.message); process.exit(2); }
  if (args.help) { console.log('usage: node tools/hub.mjs [--out site] [--games games] [--skip-invalid]'); return; }
  const out = path.resolve(args.out || path.join(ROOT, 'site'));
  const gamesDir = path.resolve(args.games || path.join(ROOT, 'games'));
  try {
    const games = buildSite({ out, gamesDir, skipInvalid: !!args['skip-invalid'] });
    console.log(`hub: built ${out} with ${games.length} game(s): ${games.map(g => g.dir).join(', ') || '(none)'}`);
  } catch (e) {
    console.error(`hub: ${e.message}`);
    process.exit(1);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
